### ISSUE TITLE
Possible color issue with C128 (flat) NTSC and VICIIdizer128

### ISSUE THREAD

**Issue by mrgw454** [c0pperdragon/LumaCode#15]
Hello there.  Using a VICIIdizer128 with a Raspberry Pi Zero 2 W on a C128 (flat) NTSC model with stock RF modulator.  Installed (extracted) Beta 62 (from https://github.com/IanSB/RGBtoHDMI/releases) to FAT32 formatted SD card.  Left everything alone with the exception of selecting the Commodore 128 Lumacode profile and setting the resolution to 1280x1024 (for my Dell 2007FP monitor).  I did not use clips to connect the luma and ground wires (I soldered them).  

I appear to have a color issue and unable to figure out why.  

I've attached a few pictures for your review (including the Color Test profile).

Using CN8 (DIN) connection (with s-video) shows correct picture and colors (and jail bars).

Any help or insight would be appreciated.  

Thank you!

-Ron

![image](https://github.com/c0pperdragon/LumaCode/assets/30988211/a277e11b-263f-48ef-89d0-a2020f61650d)
![PXL_20240202_141813327](https://github.com/c0pperdragon/LumaCode/assets/30988211/344187f7-9bbc-4f20-b243-848b5d8ddb12)
![1](https://github.com/c0pperdragon/LumaCode/assets/30988211/7ba5d764-d829-4247-8f26-521865320c7b)
![2](https://github.com/c0pperdragon/LumaCode/assets/30988211/576fcccc-0835-486d-888f-310d31532476)
![PXL_20240202_144053484](https://github.com/c0pperdragon/LumaCode/assets/30988211/fa0deb8b-98ca-4a25-b864-8538cf7db946)
![PXL_20240202_144108686](https://github.com/c0pperdragon/LumaCode/assets/30988211/da2e1e71-3b2d-4f47-ad39-49747def1dc6)

**Comment by c0pperdragon** [comment]
I am not quite sure what these pictures show me. I guess the top one is the output of the VICIIdizer128, and second the output from the A/V port? So both show basically the same blue on grey text? Is the problem the difference in exact color values? So like the blue not looking just right?
Or is there something else going on, because you would expect a green color here?

**Comment by mrgw454** [comment]
Hi.  The output is from the VICIIdizer only (picture of monitor directly) and the rest are from a capture device from the same output.  I'm trying to figure out what may be causing the blue color issue (instead of the green I would expect to see).  Output from the 8 pin DIN (not shown in any of these pictures) looks fine.  I did try another Raspberry Pi Zero (v1.1 instead of v2) and it shows the same blue color issue).  I'm guessing it may be something I did wrong, but can't seem to figure out what that may be.  Thank you for your response and help.

-Ron

**Comment by c0pperdragon** [comment]
For a simple and easy test, just put all 16 available colors on the screen at the same time to see how they look.
You can draw colored letters in BASIC, using the color switch keys (CTRL-1 to CTRL8 and Commdore-1 to Commdore-8).
Maybe I can see an error pattern then.

**Comment by c0pperdragon** [comment]
And also tell me which colors should be which.

**Comment by mrgw454** [comment]
Here's a color test.  
This image is from the actual C128 (screen capture):
![C128 Color Test](https://github.com/c0pperdragon/LumaCode/assets/30988211/32ed6479-303a-42b5-9898-f22d14ebc5ad)

This image is a picture of the monitor running the came test:
![C128 Color Test (monitor)](https://github.com/c0pperdragon/LumaCode/assets/30988211/502d761d-bb03-43ab-9396-e2c639591150)

This image is running the same color test program in Vice:
![C128 Color Test (Vice)](https://github.com/c0pperdragon/LumaCode/assets/30988211/b6565157-ed23-4b1d-9dc4-e6b024a7e6c2)

Please let me know if you need anything else and thank you!

-Ron

**Comment by c0pperdragon** [comment]
After analyzing this image it is pretty clear that the various voltage levels produced by the VICIIdizer are not quite what the RGBtoHDMI expects. Basically all levels are a bit too low. When I see this correctly on your photo this is due to the resistor R4 being 150 ohm instead of the required 180 ohm.  No idea how this got through my test procedure.
The best way to fix this would be to replace this resistor. 
But the easier  way is just to down-adjust the expected voltage levels via the RGBtoHDMI "Sample Menu". The relevant voltages are Y Hi, Y Mid, Y low. The drawback of this is that you need to do this again when you do a re-install of the software.

**Comment by mrgw454** [comment]
I really appreciate your time with this.  What settings/values do you
recommend I use for those 3  items you mentioned?

Having to reset those values at each software update is not a big deal
since it resolves the original issue.

Thank you!

-Ron

**Comment by c0pperdragon** [comment]
I can not guess which values are correct. You just need to try this until the colors get correct without flickering pixels.

**Comment by mrgw454** [comment]
Unfortunately, as soon as I start to lower the voltages (even just a couple
of values lower) the image starts to show flickering pixels and really
degrades (without any noticeable improvement in color).

The Y low seems to be really sensitive to any change at all.

At this point, perhaps I can work with you to get it exchanged?

Again, I really appreciate the help.

**Comment by c0pperdragon** [comment]
When you change the values it is very much expected to get flickering pixels until you get over the critical area and then settle on a new stable setting. 
For a solid start before fine-tuning, you need to set Y Hi to the original  value of Y Mid, then Y Mid to the original value of Y Lo and Y Lo a few numbers below its original.

**Comment by c0pperdragon** [comment]
If you have a soldering iron, you could also try to replace this resistor. I could just send you a replacement in a simple envelope.

**Comment by mrgw454** [comment]
Depending on the resistor type (smt or through hole) I'm happy to attempt a
replacement.  I do have a soldering iron and perform light duty work.  I
could probably source the resistor locally rather than have you mail one.

**Comment by mrgw454** [comment]
I will do as you suggest and let you know how it turns out.  Thank you

**Comment by mrgw454** [comment]
Latest attempt:

![Screenshot from 2024-02-03 09-05-11](https://github.com/c0pperdragon/LumaCode/assets/30988211/dd7e490e-d032-4950-aeba-8b63cff3fd82)

**Comment by c0pperdragon** [comment]
Now this looks just perfect. 
Anyway if you want, I will send you a replacement resistor  (a 0805 SMD part) if you thinkg you can swap it out. But please confirm before that this is indeed the wrong part (a 150 instead of the required 180).

**Comment by mrgw454** [comment]
I'm happy to source the part locally as I'm fortunate enough to live close
to an electronic parts supplier.  Hate to see you mail something so small
to the U.S. if you don't need to.  Where is that resistor located on the
board?

Thank you

-Ron

**Comment by c0pperdragon** [comment]
Starting from the GND output connector, R4 is the 4th resistor in the row.
