### ISSUE TITLE
Missing colors?

### ISSUE THREAD

**Issue by LarsBorris** [c0pperdragon/LumaCode#17]
Hello! 

I installed the VIC 2 DIZER mod in my breadbin and I am having problems with colors:
![c64](https://github.com/c0pperdragon/LumaCode/assets/10630935/08f49931-4088-427d-8f11-e39a49a268fa)
Any suggestions on how to resolve this?

Thanks!
(Bought the mod on tindie)

**Comment by c0pperdragon** [comment]
For a start try to check if the problem is with the VICIIdizer or the RGBtoHDMI.
Try to connect the lumacode signal from the VICIIdizer directly to a TV's composite input (normally the yellow jack).
When you paint some colored bars on the C64 basic screen, you should see something like that: 
https://github.com/c0pperdragon/LumaCode/wiki/VIC-II-dizer-(for-the-C64-computer)#details-on-color-encoding

**Comment by c0pperdragon** [comment]
Could you paint stripes of all 16 colors on the C64 screen and take a picture of the compostive video screen? Maybe I can detect the error-pattern.

**Comment by LarsBorris** [comment]
I would be happy to!
Can you supply me with the basic code/program needed to display the colors?
I have used the C64 alot but it was 30 years ago, when I was 10 years old :) 

Thanks!

**Comment by c0pperdragon** [comment]
No need for any program. Just use the color keys (press Ctrl-1/Ctrl-2  or Commdore-1/Commodore-2, etc) to switch text mode. Then write some letters in this color directly to ths screen.
Considering the general behaviour, this may actually already work, even when using the RGBtoHDMI (please check) and int may only be the problem that the screen background and border has the wrong color.

**Comment by LarsBorris** [comment]
Hello!!
![image](https://github.com/c0pperdragon/LumaCode/assets/10630935/44385858-31cf-40d1-a3b6-8abae0a516ce)

Those look fine. 
How do I type more colors? It has 16 right?

**Comment by c0pperdragon** [comment]
You can switch to futher 16 colors with the Commodore key instead the Ctrl key. But it already seems to me that the colors work in general on the RGBtoHDMI. It may really be the background color and the border that is not correctly initialized.

Try to do that by directly using one of these POKE commands:
POKE 53280,1   (or any value of 0 to 15)  for the border color
POKE 53281,1   (or any value of 0 to 15)  for the background color
Tell me how this behaves.

**Comment by LarsBorris** [comment]
Thank you, I will try that soon. 
Ran out of time (my son woke up)
Will give it a go next nap time

**Comment by LarsBorris** [comment]
I just remembered that when I had the unit hooked up with the rca video cable from the video port the color looked fine.

**Comment by LarsBorris** [comment]
![image](https://github.com/c0pperdragon/LumaCode/assets/10630935/ad2d9088-4ba8-46da-91e4-b2a87520e25a)

![image](https://github.com/c0pperdragon/LumaCode/assets/10630935/4f4785d6-6960-433a-8483-30fa6992624d)

**Comment by LarsBorris** [comment]
This is the output from the A/V output
![image](https://github.com/c0pperdragon/LumaCode/assets/10630935/c36a4758-5140-4974-accc-3a577f6b99a3)

So it must be the VICIIdizer. 
I am able to solder and have a hot air SMD station. I just haven't used as much yet. 

If it's risk free, I will gladly give it a go.

**Comment by LarsBorris** [comment]
Reflow didn't help. 
Same black background but now the text flickers between red and blue. 
https://github.com/c0pperdragon/LumaCode/assets/10630935/aef09e4a-0d97-44ea-9c3c-7f422eded82c

**Comment by LarsBorris** [comment]
I reflowed all the square chips btw just in case.

**Comment by c0pperdragon** [comment]
OK, so I guess it will be a replacement.

**Comment by LarsBorris** [comment]
Thanks! I will test the new one and report back.

**Comment by LarsBorris** [comment]
Hello!! 

Received the new board today!
I installed it and it does exactly the same as the old one (before the reflow)

I am beginning to suspect that something else is wrong. Do you have any suggestions?
Just to be sure I already did a reflow of the new board and took pictures so I could zoom in on the tiny legs. 

![image](https://github.com/c0pperdragon/LumaCode/assets/10630935/6cd9acdb-e7ba-424b-8df0-ec403f1bb0d3)

![image](https://github.com/c0pperdragon/LumaCode/assets/10630935/69fe14b7-006b-4eaa-858a-2d8ba440fb72)

This time I used my soldering iron.

**Comment by c0pperdragon** [comment]
Your reflowing looks fine, but when the replacement VICIIdizer behaves exactly as the previous one, it is extremely unlikely that this is the problem. 

Something your C64 does must be different from what all other machines do. It is impossible to tell from afar what is going on. If you have access to an oscilloscope, there my be a chance to at least get a hint on what is going on. 
First thing to check is the pixel clock generator. These sometimes create a very wonky clock signal that is somehow working with the original hardware, but causes trouble for the VICIIdizer. 
This clock is availabe on pin 22 of the VIC-II. Ideally, it should be a nice 7.88 MHz squarewave. A bit  of jitter is ok as long it is not too extreme.

**Comment by LarsBorris** [comment]
Everything works now. Turns out it was the PLA that was bad. The expansion port was also not working. Changed the PLA and now everything works. 

https://github.com/c0pperdragon/LumaCode/assets/10630935/f140e5cc-a84a-4499-877f-b75081546c2f
