### ISSUE TITLE
Question (PPUdigitizer)

### ISSUE THREAD

**Issue by ChrisCrashX** [c0pperdragon/LumaCode#22]
I will soon be installing an NESRGB mod into my NTSC NES, will the upcoming PPU Digitizer require me to remove the NESRGB board and put the PPU back in the board, or will it work with the NESRGB soldered in as well as the PPU Digitizer?

**Comment by c0pperdragon** [comment]
I did not test this, but I very much guess it should still work even with the NESRGB.

**Comment by ChrisCrashX** [comment]
Gotcha, that's reassuring, I appreciate the info and look forward to the NTSC release

**Comment by rynoweiss** [comment]
@ChrisCrashX did you ever end up doing this? Did it work?
