### ISSUE TITLE
Video capture

### ISSUE THREAD

**Issue by jp39** [c0pperdragon/LumaCode#4]
Would it be technically possible to use a video capture device to capture the output of the VIC II dizer (or equivalent), instead of plugging it to a RGB2HDMI device, and do the lumacode decoding on a PC in software ?

**Comment by c0pperdragon** [comment]
That would depend on the general capabilities of the capture device. 
You either need the possibility to perfectly sync the sample rate to the generated sub-pixels from the LumaCode source or do a very high oversampling to re-construct the sub-pixels in software.
I very much doubt that any reasonably priced capture devices can do that. That was probably the reason that the RGBtoHDMI project was created in the first place.
