### ISSUE TITLE
Request 6845/6847 Lumacode support

### ISSUE THREAD

**Issue by oe7twj** [c0pperdragon/LumaCode#6]
It would be nice to have a Lumacode solution for Motorola 6847 based computers.

This would include some homecomputers:
- Tandy CoCo1 and CoCo2 (https://en.wikipedia.org/wiki/TRS-80_Color_Computer)
- Dragon32 and Dragon 64 (https://de.wikipedia.org/wiki/Dragon_32,_Dragon_64#Grafik,_Ton,_Ein-_und_Ausgabe)

The CoCo 3 has much more colors with a newer video chip, I'm not sure if this is possible ...

But some old computers use monochrome CRT like the Commodore PET.
The video chip used here is a Motorola 6845.
If CRT dies the PET computer dies, it is not easy to get a new CRT.
So this would be a nice methode to repair such computers.

**Comment by c0pperdragon** [comment]
The computers you mention already have good support by the RGBtoHDMI system when using a full analog input variant (not just luminance). Some will need slight modification of he computer. Details can be found here: https://github.com/hoglet67/RGBtoHDMI/wiki/Cables
