### ISSUE TITLE
Request for Vic-20 NTSC

### ISSUE THREAD

**Issue by jc13git** [c0pperdragon/LumaCode#9]
Hello @c0pperdragon,

I saw on your Tindie store that the Vic-20-Dizer is only PAL for the moment and wanted to ask if an NTSC version was in the works.

Thanks for your hard work on this project!

**Comment by c0pperdragon** [comment]
Yes. Luckily one user is so kind to borrow me an NTSC VIC. Once I have this I will try to make my board work with this also.

**Comment by jc13git** [comment]
That's great news - one more question if you don't mind.  I just recently ordered a VicII-dizer and a Vic20-dizer (PAL) from your Tindie site.  I would like to put the NTSC code on it when you have it working if that's possible -  I'd be willing to help with testing if you need it.  Thanks again.

**Comment by c0pperdragon** [comment]
No, sorry. 
The firmware that needs to be flashed onto the part is my most valuable asset and strictly confidential. No way to protect my IP in any other way.

**Comment by jc13git** [comment]
Understood - thanks!
